# Generated by Django 5.2.5 on 2026-01-20 20:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Paket Adı')),
                ('display_name', models.CharField(max_length=100, verbose_name='Görünen Ad')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sms_credits', models.PositiveIntegerField(help_text='Bu pakette kaç SMS kredisi var', validators=[django.core.validators.MinValueValidator(1)], verbose_name='SMS Kredisi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Fiyat (TL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan paketler daha görünür bir şekilde gösterilir', verbose_name='Öne Çıkan')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('bonus_credits', models.PositiveIntegerField(default=0, help_text='Bu paketi alan işletmelere verilen ekstra SMS kredisi', verbose_name='Bonus Kredi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Package',
                'verbose_name_plural': 'SMS Packages',
                'ordering': ['sort_order', 'sms_credits'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='system_subs_is_acti_0d0764_idx'), models.Index(fields=['sms_credits'], name='system_subs_sms_cre_7d270f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='Billing Cycle')),
                ('max_employee', models.IntegerField(verbose_name='Max Employees')),
                ('max_locations', models.IntegerField(verbose_name='Max Locations')),
                ('max_appointments_per_month', models.IntegerField(blank=True, null=True, verbose_name='Max Appointments Per Month')),
                ('has_online_booking', models.BooleanField(default=True, verbose_name='Has Online Booking')),
                ('has_sms_notifications', models.BooleanField(default=False, verbose_name='Has SMS Notifications')),
                ('has_analytics', models.BooleanField(default=False, verbose_name='Has Analytics')),
                ('features', models.JSONField(blank=True, default=dict, help_text="Format: {'custom_roles': bool, 'automation': bool, 'advanced_reports': bool, 'api_access': bool, 'google_calendar': bool, 'reserve_with_google': bool, 'sms_notifications': bool, 'email_notifications': bool}", verbose_name='Features')),
                ('welcome_sms_bonus', models.PositiveIntegerField(default=100, help_text='SMS credits given to new tenants when they start with this plan', verbose_name='Welcome SMS Bonus')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'billing_cycle'], name='system_subs_is_acti_ae4507_idx'), models.Index(fields=['billing_cycle', 'price'], name='system_subs_billing_41cfa4_idx')],
            },
        ),
    ]
