# Generated by Django 5.2.5 on 2026-01-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='welcome_sms_bonus',
            field=models.PositiveIntegerField(default=100, help_text='SMS credits given to new tenants when they start with this plan', verbose_name='Welcome SMS Bonus'),
        ),
    ]
