# Generated by Django 5.2.5 on 2026-01-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["is_active", "billing_cycle"],
                name="system_subs_is_acti_ae4507_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["billing_cycle", "price"], name="system_subs_billing_41cfa4_idx"
            ),
        ),
    ]
