"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# apps/ klasörünü Python path'ine ekle
sys.path.insert(0, str(BASE_DIR / 'apps'))


# =============================================================================
# ENVIRONMENT CONFIGURATION
# =============================================================================

env = environ.Env(
    DEBUG=(bool, True),
    SECRET_KEY=(str, 'django-insecure-change-this-in-production'),
    DATABASE_URL=(str, ''),
)

# Environment detection: Docker (env vars) vs cPanel (.env files)
if 'DEBUG' not in os.environ:
    env_type = os.environ.get('DJANGO_ENV', 'development')
    env_file = {
        'staging': '.env.staging',
        'production': '.env.prod',
    }.get(env_type, '.env')

    # Try parent directory first, then backend directory
    for env_path in [BASE_DIR.parent / env_file, BASE_DIR / env_file,
                     BASE_DIR.parent / '.env', BASE_DIR / '.env']:
        if env_path.exists():
            environ.Env.read_env(env_path)
            break

CURRENT_ENV = env('DJANGO_ENV', default='development')


# =============================================================================
# CORE DJANGO SETTINGS
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# Allowed hosts
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    allowed_hosts_str = env('ALLOWED_HOSTS', default='localhost,127.0.0.1')
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',')]
    domain = env('DOMAIN', default='')
    if domain and domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(domain)


# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
    'django_summernote',
    'django_filters',
    'drf_spectacular',

    # Local apps
    'core',
    'accounts',
    'system',
    'providers',
    'tenants',
    'billing',
    'staff',
    'clients',
    'notifications',
    'pages',
    'posts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# =============================================================================
# DATABASE
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# =============================================================================

if env('DATABASE_URL'):
    import dj_database_url
    DATABASES = {'default': dj_database_url.parse(env('DATABASE_URL'))}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# =============================================================================
# AUTHENTICATION
# =============================================================================

AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =============================================================================
# INTERNATIONALIZATION
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# =============================================================================

LANGUAGE_CODE = 'tr'
LANGUAGES = [
    ('tr', 'Türkçe'),
    ('en', 'English'),
]

TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = [BASE_DIR / 'locale']


# =============================================================================
# STATIC & MEDIA FILES
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# =============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files handler: django, whitenoise, s3, caddy, nginx
STATIC_FILES_HANDLER = env('STATIC_FILES_HANDLER', default='django' if DEBUG else 'caddy')

if STATIC_FILES_HANDLER == 'whitenoise':
    MIDDLEWARE.insert(2, 'whitenoise.middleware.WhiteNoiseMiddleware')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = DEBUG
    WHITENOISE_MAX_AGE = 86400

elif STATIC_FILES_HANDLER == 's3':
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='us-east-1')
    AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN', default=None)
    AWS_DEFAULT_ACL = env('AWS_DEFAULT_ACL', default='public-read')
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False
    if AWS_S3_CUSTOM_DOMAIN:
        STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'


# =============================================================================
# DEFAULT PRIMARY KEY
# =============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# REDIS, CACHE & CELERY
# =============================================================================

def _check_redis():
    """Check Redis connection availability"""
    try:
        import redis
        redis_url = env('REDIS_URL', default='redis://redis:6379/0')
        if redis_url.startswith('redis://'):
            parts = redis_url.replace('redis://', '').split(':')
            host = parts[0]
            port_db = parts[1].split('/')
            port = int(port_db[0])
            db = int(port_db[1]) if len(port_db) > 1 else 0
        else:
            host, port, db = 'localhost', 6379, 0
        redis.Redis(host=host, port=port, db=db, socket_timeout=2).ping()
        return True
    except Exception:
        return False

REDIS_AVAILABLE = _check_redis()

# Cache
if REDIS_AVAILABLE:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': env('REDIS_URL', default='redis://redis:6379/1'),
            'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'}
        }
    }
else:
    cache_backend = env('FALLBACK_CACHE_BACKEND', default='dummy')
    CACHES = {
        'default': {
            'BACKEND': {
                'database': 'django.core.cache.backends.db.DatabaseCache',
                'locmem': 'django.core.cache.backends.locmem.LocMemCache',
            }.get(cache_backend, 'django.core.cache.backends.dummy.DummyCache'),
            'LOCATION': 'django_cache_table' if cache_backend == 'database' else 'unique-snowflake',
        }
    }

# Celery
CELERY_ENABLED = REDIS_AVAILABLE and env.bool('CELERY_ENABLED', default=False)

if REDIS_AVAILABLE:
    CELERY_BROKER_URL = env('REDIS_URL', default='redis://redis:6379/0')
    CELERY_RESULT_BACKEND = env('REDIS_URL', default='redis://redis:6379/0')
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = TIME_ZONE


# =============================================================================
# SECURITY (Production)
# =============================================================================

if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 86400
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # SECURE_SSL_REDIRECT = True
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True


# =============================================================================
# CORS
# =============================================================================

FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:3000')

if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ]
else:
    domain = env('DOMAIN', default='yourdomain.com')
    CORS_ALLOWED_ORIGINS = [
        f"https://{domain}",
        f"https://www.{domain}",
    ]

CORS_ALLOW_CREDENTIALS = True


# =============================================================================
# REST FRAMEWORK & JWT
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'login': '10/hour',
        'register': '5/hour',
        'password_reset': '3/hour',
        'email_verify': '5/hour',
        'token_refresh': '20/hour',
        'social_auth': '10/hour',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


# =============================================================================
# EMAIL & NOTIFICATION PROVIDERS
# =============================================================================

# Provider selection
EMAIL_PROVIDER = env('EMAIL_PROVIDER', default='mock')  # smtp, sendgrid, mock
SMS_PROVIDER = env('SMS_PROVIDER', default='mock')      # netgsm, twilio, mock

# Email backend (based on provider)
if EMAIL_PROVIDER == 'mock':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
elif EMAIL_PROVIDER == 'sendgrid':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.SMTPBackend'
else:  # smtp
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.SMTPBackend'

# SMTP settings (used when EMAIL_PROVIDER=smtp)
EMAIL_HOST = env('EMAIL_HOST', default='localhost')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@example.com')

# SendGrid (used when EMAIL_PROVIDER=sendgrid)
SENDGRID_API_KEY = env('SENDGRID_API_KEY', default='')

# NetGSM (used when SMS_PROVIDER=netgsm)
NETGSM_USERNAME = env('NETGSM_USERNAME', default='')
NETGSM_PASSWORD = env('NETGSM_PASSWORD', default='')
NETGSM_HEADER = env('NETGSM_HEADER', default='')

# Twilio (used when SMS_PROVIDER=twilio)
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_FROM_NUMBER = env('TWILIO_FROM_NUMBER', default='')

# Push Notifications (FCM)
FCM_SERVER_KEY = env('FCM_SERVER_KEY', default='')


# =============================================================================
# OAUTH PROVIDERS
# =============================================================================

# Google
GOOGLE_OAUTH2_CLIENT_ID = env('GOOGLE_OAUTH2_CLIENT_ID', default='')
GOOGLE_OAUTH2_CLIENT_SECRET = env('GOOGLE_OAUTH2_CLIENT_SECRET', default='')

# Facebook
FACEBOOK_APP_ID = env('FACEBOOK_APP_ID', default='')
FACEBOOK_APP_SECRET = env('FACEBOOK_APP_SECRET', default='')

# Apple
APPLE_CLIENT_ID = env('APPLE_CLIENT_ID', default='')
APPLE_SECRET = env('APPLE_SECRET', default='')
APPLE_KEY_ID = env('APPLE_KEY_ID', default='')
APPLE_TEAM_ID = env('APPLE_TEAM_ID', default='')


# =============================================================================
# PAYMENT GATEWAY
# =============================================================================

IYZICO_API_KEY = env('IYZICO_API_KEY', default='sandbox-api-key')
IYZICO_SECRET_KEY = env('IYZICO_SECRET_KEY', default='sandbox-secret-key')
IYZICO_TEST_MODE = env.bool('IYZICO_TEST_MODE', default=DEBUG)


# =============================================================================
# MULTI-TENANT
# =============================================================================

SUPERUSER_BYPASS_TENANT = env.bool('SUPERUSER_BYPASS_TENANT', default=True)


# =============================================================================
# MONITORING
# =============================================================================

SENTRY_DSN = env('SENTRY_DSN', default='')
APP_VERSION = env('APP_VERSION', default='1.0.0')

# Uncomment to enable Sentry
# if SENTRY_DSN and not DEBUG:
#     import sentry_sdk
#     from sentry_sdk.integrations.django import DjangoIntegration
#     sentry_sdk.init(
#         dsn=SENTRY_DSN,
#         integrations=[DjangoIntegration()],
#         traces_sample_rate=0.1,
#         environment=CURRENT_ENV,
#         release=APP_VERSION,
#     )


# =============================================================================
# THIRD-PARTY APPS
# =============================================================================

# Django Summernote (Rich Text Editor)
SUMMERNOTE_CONFIG = {
    'summernote': {
        'height': '480',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
        'lang': 'tr-TR',
    },
    'attachment_require_authentication': True,
    'attachment_filesize_limit': 1024 * 1024 * 10,  # 10MB
    'attachment_absolute_uri': False,
}


# =============================================================================
# LOGGING
# =============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '\n[{levelname}] {name}:\n{message}\n',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        # Provider loggers (SMS/Email mock output)
        'providers': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'providers.sms': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'providers.email': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'notifications': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# =============================================================================
# ENVIRONMENT INFO (Development only)
# =============================================================================

if DEBUG:
    print(f"[INFO] Environment: {CURRENT_ENV}")
    print(f"[INFO] Redis: {'Available' if REDIS_AVAILABLE else 'Not available'}")
    print(f"[INFO] Celery: {'Enabled' if CELERY_ENABLED else 'Disabled'}")
