# Generated by Django 5.2.5 on 2026-01-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name or CSS class (e.g., 'salon', 'barbershop')",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Type",
                "verbose_name_plural": "Business Types",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DefaultPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'cash', 'credit_card', 'bank_transfer')",
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icon"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Default Payment Method",
                "verbose_name_plural": "Default Payment Methods",
                "ordering": ["order", "name"],
            },
        ),
    ]
