# Generated by Django 5.2.5 on 2026-01-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesstype",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon name or CSS class (e.g., 'salon', 'barbershop')",
                max_length=50,
                verbose_name="Icon",
            ),
        ),
    ]
