# Generated by Django 5.2.5 on 2026-02-03 21:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=True, verbose_name="SMS Enabled"),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="Email Enabled"),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(default=True, verbose_name="In-App Enabled"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, verbose_name="Push Enabled"),
                ),
                (
                    "type_preferences",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Type Preferences"
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Quiet Hours Enabled"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        default=datetime.time(22, 0), verbose_name="Quiet Start"
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        default=datetime.time(8, 0), verbose_name="Quiet End"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="True if sent by platform",
                        verbose_name="System Notification",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system_announcement", "System Announcement"),
                            ("billing_alert", "Billing Alert"),
                            ("sms_credit_low", "SMS Credit Low"),
                            ("sms_credit_depleted", "SMS Credit Depleted"),
                            ("subscription_expiry", "Subscription Expiry"),
                            ("subscription_expired", "Subscription Expired"),
                            ("feature_update", "Feature Update"),
                            ("appointment_new", "New Appointment"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                            ("appointment_updated", "Appointment Updated"),
                            (
                                "appointment_reminder_staff",
                                "Appointment Reminder (Staff)",
                            ),
                            ("client_new", "New Client"),
                            ("task_assigned", "Task Assigned"),
                            ("appointment_confirmation", "Appointment Confirmation"),
                            ("appointment_reminder", "Appointment Reminder"),
                            (
                                "appointment_cancelled_client",
                                "Appointment Cancelled (Client)",
                            ),
                            ("birthday_greeting", "Birthday Greeting"),
                            ("campaign", "Campaign"),
                            ("feedback_request", "Feedback Request"),
                            ("custom", "Custom Message"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Action URL"
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Action Label"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
                (
                    "sender_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to="tenants.company",
                        verbose_name="Sender Company",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notificatio_recipie_684eac_idx",
                    ),
                    models.Index(
                        fields=["recipient", "notification_type"],
                        name="notificatio_recipie_028906_idx",
                    ),
                    models.Index(
                        fields=["sender_company", "-created_at"],
                        name="notificatio_sender__970261_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier, e.g., appointment_reminder",
                        max_length=50,
                        verbose_name="Code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system_announcement", "System Announcement"),
                            ("billing_alert", "Billing Alert"),
                            ("sms_credit_low", "SMS Credit Low"),
                            ("sms_credit_depleted", "SMS Credit Depleted"),
                            ("subscription_expiry", "Subscription Expiry"),
                            ("subscription_expired", "Subscription Expired"),
                            ("feature_update", "Feature Update"),
                            ("appointment_new", "New Appointment"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                            ("appointment_updated", "Appointment Updated"),
                            (
                                "appointment_reminder_staff",
                                "Appointment Reminder (Staff)",
                            ),
                            ("client_new", "New Client"),
                            ("task_assigned", "Task Assigned"),
                            ("appointment_confirmation", "Appointment Confirmation"),
                            ("appointment_reminder", "Appointment Reminder"),
                            (
                                "appointment_cancelled_client",
                                "Appointment Cancelled (Client)",
                            ),
                            ("birthday_greeting", "Birthday Greeting"),
                            ("campaign", "Campaign"),
                            ("feedback_request", "Feedback Request"),
                            ("custom", "Custom Message"),
                        ],
                        max_length=50,
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="SMS Enabled"),
                ),
                (
                    "sms_template",
                    models.TextField(
                        blank=True,
                        help_text="Use {{ variable }} for placeholders. Max 160 chars.",
                        verbose_name="SMS Template",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=False, verbose_name="Email Enabled"),
                ),
                (
                    "email_subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Email Subject"
                    ),
                ),
                (
                    "email_body_text",
                    models.TextField(blank=True, verbose_name="Email Body (Text)"),
                ),
                (
                    "email_body_html",
                    models.TextField(blank=True, verbose_name="Email Body (HTML)"),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(default=False, verbose_name="In-App Enabled"),
                ),
                (
                    "in_app_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="In-App Title"
                    ),
                ),
                (
                    "in_app_message",
                    models.TextField(blank=True, verbose_name="In-App Message"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=False, verbose_name="Push Enabled"),
                ),
                (
                    "push_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Push Title"
                    ),
                ),
                (
                    "push_body",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Push Body"
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Default Priority",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"client_name": "Client full name", "date": "Appointment date"}',
                        verbose_name="Variables",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for system-wide templates",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="tenants.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["code"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("in_app", "In-App"),
                            ("push", "Push"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Name"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("system_announcement", "System Announcement"),
                            ("billing_alert", "Billing Alert"),
                            ("sms_credit_low", "SMS Credit Low"),
                            ("sms_credit_depleted", "SMS Credit Depleted"),
                            ("subscription_expiry", "Subscription Expiry"),
                            ("subscription_expired", "Subscription Expired"),
                            ("feature_update", "Feature Update"),
                            ("appointment_new", "New Appointment"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                            ("appointment_updated", "Appointment Updated"),
                            (
                                "appointment_reminder_staff",
                                "Appointment Reminder (Staff)",
                            ),
                            ("client_new", "New Client"),
                            ("task_assigned", "Task Assigned"),
                            ("appointment_confirmation", "Appointment Confirmation"),
                            ("appointment_reminder", "Appointment Reminder"),
                            (
                                "appointment_cancelled_client",
                                "Appointment Cancelled (Client)",
                            ),
                            ("birthday_greeting", "Birthday Greeting"),
                            ("campaign", "Campaign"),
                            ("feedback_request", "Feedback Request"),
                            ("custom", "Custom Message"),
                        ],
                        max_length=50,
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subject"
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "content_html",
                    models.TextField(blank=True, verbose_name="HTML Content"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Provider"
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Provider Message ID",
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Provider Response"
                    ),
                ),
                (
                    "credits_used",
                    models.PositiveIntegerField(default=0, verbose_name="Credits Used"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Scheduled At"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered At"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Opened At"
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Clicked At"
                    ),
                ),
                (
                    "open_count",
                    models.PositiveIntegerField(default=0, verbose_name="Open Count"),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(default=0, verbose_name="Click Count"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Retry Count"),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(default=3, verbose_name="Max Retries"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sent By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbound Message",
                "verbose_name_plural": "Outbound Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "channel", "status", "-created_at"],
                        name="notificatio_company_13846d_idx",
                    ),
                    models.Index(
                        fields=["company", "-created_at"],
                        name="notificatio_company_8dc4ee_idx",
                    ),
                    models.Index(
                        fields=["recipient_phone", "-created_at"],
                        name="notificatio_recipie_bcdd1d_idx",
                    ),
                    models.Index(
                        fields=["recipient_email", "-created_at"],
                        name="notificatio_recipie_a9320b_idx",
                    ),
                ],
            },
        ),
    ]
