# Generated by Django 5.2.5 on 2026-01-20 20:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_billing', '0001_initial'),
        ('system_subscriptions', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_subscriptions', to='system_subscriptions.subscriptionplan', verbose_name='New Plan')),
                ('old_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_subscriptions', to='system_subscriptions.subscriptionplan', verbose_name='Old Plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='tenants.company', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Auto Renew')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Original Price')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discounted Price')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_subscriptions.subscriptionplan', verbose_name='Plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.company', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tenant Subscription',
                'verbose_name_plural': 'Tenant Subscriptions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='Current SMS credit balance', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_balance', to='tenants.company', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'SMS Balance',
                'verbose_name_plural': 'SMS Balances',
                'indexes': [models.Index(fields=['tenant'], name='tenant_subs_tenant__2a33f1_idx'), models.Index(fields=['balance'], name='tenant_subs_balance_2b202c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage'), ('refund', 'Refund'), ('admin_adjustment', 'Admin Adjustment'), ('bonus', 'Bonus')], max_length=20, verbose_name='Transaction Type')),
                ('amount', models.IntegerField(help_text='Positive for additions, negative for deductions', verbose_name='Amount')),
                ('balance_after', models.IntegerField(help_text='SMS balance after this transaction', verbose_name='Balance After')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction data', verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_transactions', to='system_billing.payment', verbose_name='Payment')),
                ('sms_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_subscriptions.smspackage', verbose_name='SMS Package')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_transactions', to='tenants.company', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'SMS Transaction',
                'verbose_name_plural': 'SMS Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='tenant_subs_tenant__5f375b_idx'), models.Index(fields=['transaction_type'], name='tenant_subs_transac_bf395f_idx'), models.Index(fields=['-created_at'], name='tenant_subs_created_1b9d90_idx')],
            },
        ),
    ]
