# Generated by Django 5.2.5 on 2026-01-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(default=False, verbose_name="Maintenance Mode"),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Support Email"
                    ),
                ),
                (
                    "system_currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="System Currency"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Contact Phone"
                    ),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, verbose_name="Website URL"),
                ),
                (
                    "terms_url",
                    models.URLField(blank=True, verbose_name="Terms & Conditions URL"),
                ),
                (
                    "privacy_url",
                    models.URLField(blank=True, verbose_name="Privacy Policy URL"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Settings",
                "verbose_name_plural": "Global Settings",
            },
        ),
    ]
