# Generated by Django 5.2.5 on 2026-01-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='trial_period_days',
            field=models.PositiveIntegerField(default=365, help_text='Number of days for new tenant trial period', verbose_name='Trial Period (Days)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='welcome_sms_bonus',
            field=models.PositiveIntegerField(default=10, help_text='SMS credits given to new tenants as welcome bonus', verbose_name='Welcome SMS Bonus'),
        ),
    ]
