# Generated by Django 5.2.5 on 2026-01-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_tenant_provisioning_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='trial_period_days',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='welcome_sms_bonus',
        ),
    ]
