# Generated by Django 5.2.5 on 2026-01-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Provider Name')),
                ('code', models.CharField(help_text='Unique identifier (e.g., netgsm, twilio, sendgrid)', max_length=50, unique=True, verbose_name='Provider Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority', verbose_name='Priority')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-specific configuration (API keys, credentials, etc.)', verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Provider',
                'verbose_name_plural': 'Email Providers',
            },
        ),
        migrations.CreateModel(
            name='PushProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Provider Name')),
                ('code', models.CharField(help_text='Unique identifier (e.g., netgsm, twilio, sendgrid)', max_length=50, unique=True, verbose_name='Provider Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority', verbose_name='Priority')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-specific configuration (API keys, credentials, etc.)', verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Push Provider',
                'verbose_name_plural': 'Push Providers',
            },
        ),
        migrations.CreateModel(
            name='SmsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Provider Name')),
                ('code', models.CharField(help_text='Unique identifier (e.g., netgsm, twilio, sendgrid)', max_length=50, unique=True, verbose_name='Provider Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority', verbose_name='Priority')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-specific configuration (API keys, credentials, etc.)', verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Provider',
                'verbose_name_plural': 'SMS Providers',
            },
        ),
    ]
