# Generated by Django 5.2.5 on 2026-01-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('smtp', 'SMTP'), ('sendgrid', 'Sendgrid'), ('mock', 'Mock (Test)')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('credentials', models.JSONField(default=dict)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Provider Configuration',
                'verbose_name_plural': 'Email Provider Configurations',
            },
        ),
        migrations.CreateModel(
            name='SMSProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('netgsm', 'NetGSM'), ('twilio', 'Twilio'), ('mock', 'Mock (Test)')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('credentials', models.JSONField(default=dict, help_text='API keys, passwords, etc.')),
                ('settings', models.JSONField(default=dict, help_text='Rate limits, retry config, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Provider Configuration',
                'verbose_name_plural': 'SMS Provider Configurations',
            },
        ),
    ]
