# Generated by Django 5.2.5 on 2026-01-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("smtp", "SMTP"),
                            ("sendgrid", "Sendgrid"),
                            ("mock", "Mock (Test)"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "credentials",
                    models.JSONField(
                        default=dict,
                        help_text='SMTP: {"host": "", "port": 587, "username": "", "password": ""}',
                        verbose_name="Credentials",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"from_email": "noreply@app.com", "from_name": "App"}',
                        verbose_name="Settings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Provider Config",
                "verbose_name_plural": "Email Provider Configs",
            },
        ),
        migrations.CreateModel(
            name="SMSProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("netgsm", "NetGSM"),
                            ("twilio", "Twilio"),
                            ("mock", "Mock (Test)"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "credentials",
                    models.JSONField(
                        default=dict,
                        help_text='{"username": "xxx", "password": "xxx", "sender_id": "SALON"}',
                        verbose_name="Credentials",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"rate_limit": 100, "retry_count": 3}',
                        verbose_name="Settings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SMS Provider Config",
                "verbose_name_plural": "SMS Provider Configs",
            },
        ),
    ]
