# Generated by Django 5.2.5 on 2026-01-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailproviderconfig",
            options={
                "verbose_name": "Email Provider Config",
                "verbose_name_plural": "Email Provider Configs",
            },
        ),
        migrations.AlterModelOptions(
            name="smsproviderconfig",
            options={
                "verbose_name": "SMS Provider Config",
                "verbose_name_plural": "SMS Provider Configs",
            },
        ),
        migrations.AlterField(
            model_name="emailproviderconfig",
            name="credentials",
            field=models.JSONField(
                default=dict,
                help_text='SMTP: {"host": "", "port": 587, "username": "", "password": ""}',
                verbose_name="Credentials",
            ),
        ),
        migrations.AlterField(
            model_name="emailproviderconfig",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"from_email": "noreply@app.com", "from_name": "App"}',
                verbose_name="Settings",
            ),
        ),
        migrations.AlterField(
            model_name="smsproviderconfig",
            name="credentials",
            field=models.JSONField(
                default=dict,
                help_text='{"username": "xxx", "password": "xxx", "sender_id": "SALON"}',
                verbose_name="Credentials",
            ),
        ),
        migrations.AlterField(
            model_name="smsproviderconfig",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"rate_limit": 100, "retry_count": 3}',
                verbose_name="Settings",
            ),
        ),
    ]
