# Generated by Django 5.2.5 on 2025-09-11 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL/Slug"
                    ),
                ),
                ("content", models.TextField(verbose_name="Gövde")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Yayınlanmış mı?"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="pages.page",
                        verbose_name="Üst Sayfa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sayfa",
                "verbose_name_plural": "Sayfalar",
                "ordering": ["order", "title"],
            },
        ),
    ]
