# Generated by Django 5.2.5 on 2026-01-29 20:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Display Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "sms_credits",
                    models.PositiveIntegerField(
                        help_text="Number of SMS credits in this package",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="SMS Credits",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured packages are displayed more prominently",
                        verbose_name="Is Featured",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "bonus_credits",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Extra SMS credits given with this package",
                        verbose_name="Bonus Credits",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "SMS Package",
                "verbose_name_plural": "SMS Packages",
                "ordering": ["sort_order", "sms_credits"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="billing_sms_is_acti_ff3b22_idx",
                    ),
                    models.Index(
                        fields=["sms_credits"], name="billing_sms_sms_cre_b7ada8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=20,
                        verbose_name="Billing Cycle",
                    ),
                ),
                (
                    "max_employees",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum number of team members",
                        verbose_name="Max Employees",
                    ),
                ),
                (
                    "max_products",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="null = unlimited",
                        null=True,
                        verbose_name="Max Products",
                    ),
                ),
                (
                    "has_inventory",
                    models.BooleanField(
                        default=False,
                        help_text="Product stock tracking",
                        verbose_name="Inventory Module",
                    ),
                ),
                (
                    "extended_features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional features: {'white_label': bool, 'custom_domain': bool, 'priority_support': bool}",
                        verbose_name="Extended Features",
                    ),
                ),
                (
                    "welcome_sms_bonus",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="SMS credits given to new tenants when they start with this plan",
                        verbose_name="Welcome SMS Bonus",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight this plan in pricing pages",
                        verbose_name="Is Featured",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["sort_order", "price"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "billing_cycle"],
                        name="billing_sub_is_acti_94429e_idx",
                    ),
                    models.Index(
                        fields=["billing_cycle", "price"],
                        name="billing_sub_billing_5f72e9_idx",
                    ),
                    models.Index(fields=["slug"], name="billing_sub_slug_8fdb4d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Changed At"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_history",
                        to="tenants.company",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "new_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_subscriptions",
                        to="billing.subscriptionplan",
                        verbose_name="New Plan",
                    ),
                ),
                (
                    "old_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_subscriptions",
                        to="billing.subscriptionplan",
                        verbose_name="Old Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription History",
                "verbose_name_plural": "Subscription Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "auto_renew",
                    models.BooleanField(default=False, verbose_name="Auto Renew"),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Original Price",
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Discounted Price",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.subscriptionplan",
                        verbose_name="Plan",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenants.company",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Subscription",
                "verbose_name_plural": "Tenant Subscriptions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription Payment"),
                            ("sms_package", "SMS Package Payment"),
                        ],
                        max_length=20,
                        verbose_name="Payment Type",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("iyzico", "iyzico Checkout Form"),
                            ("bank_transfer", "Bank Transfer"),
                            ("eft", "EFT"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("disputed", "Disputed"),
                            ("chargeback", "Chargeback"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "gateway_name",
                    models.CharField(
                        default="iyzico",
                        help_text="Payment provider: iyzico, stripe, paypal, etc.",
                        max_length=50,
                        verbose_name="Payment Gateway",
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Universal transaction ID from payment gateway",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Gateway Transaction ID",
                    ),
                ),
                (
                    "gateway_token",
                    models.CharField(
                        blank=True,
                        help_text="Checkout session or payment token",
                        max_length=255,
                        null=True,
                        verbose_name="Gateway Token",
                    ),
                ),
                (
                    "gateway_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Gateway-specific data: conversation_id, fraud_status, etc.",
                        verbose_name="Gateway Data",
                    ),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="payment_proofs/",
                        verbose_name="Payment Proof",
                    ),
                ),
                (
                    "bank_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Bank Reference",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Store full iyzico response and other metadata",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="tenants.company",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "sms_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.smspackage",
                        verbose_name="SMS Package",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.tenantsubscription",
                        verbose_name="Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale Invoice"),
                            ("refund", "Refund Invoice"),
                        ],
                        default="sale",
                        max_length=20,
                        verbose_name="Invoice Type",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Invoice Number"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Invoice Date")),
                (
                    "invoice_file",
                    models.FileField(
                        upload_to="invoices/", verbose_name="Invoice File"
                    ),
                ),
                (
                    "tax_office",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tax Office"
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tax Number"
                    ),
                ),
                (
                    "company_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Company Title"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="billing.payment",
                        verbose_name="Payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-invoice_date"],
                "indexes": [
                    models.Index(
                        fields=["payment", "invoice_type"],
                        name="billing_inv_payment_960d27_idx",
                    ),
                    models.Index(
                        fields=["invoice_number"], name="billing_inv_invoice_70511c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SmsBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(
                        default=0,
                        help_text="Current SMS credit balance",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Balance",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_balance",
                        to="tenants.company",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Balance",
                "verbose_name_plural": "SMS Balances",
                "indexes": [
                    models.Index(
                        fields=["tenant"], name="billing_sms_tenant__0e5eea_idx"
                    ),
                    models.Index(
                        fields=["balance"], name="billing_sms_balance_0ef931_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SmsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("usage", "Usage"),
                            ("refund", "Refund"),
                            ("admin_adjustment", "Admin Adjustment"),
                            ("bonus", "Bonus"),
                        ],
                        max_length=20,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Positive for additions, negative for deductions",
                        verbose_name="Amount",
                    ),
                ),
                (
                    "balance_after",
                    models.IntegerField(
                        help_text="SMS balance after this transaction",
                        verbose_name="Balance After",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional transaction data",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_transactions",
                        to="billing.payment",
                        verbose_name="Payment",
                    ),
                ),
                (
                    "sms_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.smspackage",
                        verbose_name="SMS Package",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_transactions",
                        to="tenants.company",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Transaction",
                "verbose_name_plural": "SMS Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="billing_sms_tenant__162332_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="billing_sms_transac_99f7e9_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="billing_sms_created_5aca1e_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "status"], name="billing_pay_tenant__9b948c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["gateway_transaction_id"], name="billing_pay_gateway_a1f2ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "payment_type"], name="billing_pay_status_e39623_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["gateway_name", "status"], name="billing_pay_gateway_139ed6_idx"
            ),
        ),
    ]
