# Generated by Django 5.2.5 on 2026-01-13 20:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant_subscriptions", "0001_initial"),
        ("tenants", "0002_companyrolepermission_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription Payment"),
                            ("sms_package", "SMS Package Payment"),
                        ],
                        max_length=20,
                        verbose_name="Payment Type",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("iyzico", "iyzico Checkout Form"),
                            ("bank_transfer", "Bank Transfer"),
                            ("eft", "EFT"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("disputed", "Disputed"),
                            ("chargeback", "Chargeback"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "gateway_name",
                    models.CharField(
                        default="iyzico",
                        help_text="Payment provider: iyzico, stripe, paypal, etc.",
                        max_length=50,
                        verbose_name="Payment Gateway",
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Universal transaction ID from payment gateway",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Gateway Transaction ID",
                    ),
                ),
                (
                    "gateway_token",
                    models.CharField(
                        blank=True,
                        help_text="Checkout session or payment token",
                        max_length=255,
                        null=True,
                        verbose_name="Gateway Token",
                    ),
                ),
                (
                    "gateway_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Gateway-specific data: conversation_id, fraud_status, etc.",
                        verbose_name="Gateway Data",
                    ),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="payment_proofs/",
                        verbose_name="Payment Proof",
                    ),
                ),
                (
                    "bank_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Bank Reference",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Store full iyzico response and other metadata",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="tenant_subscriptions.tenantsubscription",
                        verbose_name="Subscription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="tenants.company",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale Invoice"),
                            ("refund", "Refund Invoice"),
                        ],
                        default="sale",
                        max_length=20,
                        verbose_name="Invoice Type",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Invoice Number"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Invoice Date")),
                (
                    "invoice_file",
                    models.FileField(
                        upload_to="invoices/", verbose_name="Invoice File"
                    ),
                ),
                (
                    "tax_office",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tax Office"
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tax Number"
                    ),
                ),
                (
                    "company_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Company Title"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="system_billing.payment",
                        verbose_name="Payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "status"], name="system_bill_tenant__190081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["gateway_transaction_id"], name="system_bill_gateway_eafa14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "payment_type"], name="system_bill_status_e6e554_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["gateway_name", "status"], name="system_bill_gateway_0e3f8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["payment", "invoice_type"],
                name="system_bill_payment_c1185e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="system_bill_invoice_155571_idx"
            ),
        ),
    ]
