# Generated by Django 5.2.5 on 2026-01-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_billing", "0001_initial"),
        (
            "system_subscriptions",
            "0002_subscriptionplan_system_subs_is_acti_ae4507_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="sms_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="system_subscriptions.smspackage",
                verbose_name="SMS Package",
            ),
        ),
    ]
