# Generated by Django 5.2.5 on 2026-02-03 21:20

import core.utils
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region="TR",
                        validators=[
                            core.utils.ValidationUtils.validate_phone_supported
                        ],
                        verbose_name="Phone",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("unspecified", "Unspecified"),
                        ],
                        default="unspecified",
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="General notes about the client.",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "accepts_marketing",
                    models.BooleanField(
                        default=False,
                        help_text="Does the client consent to receive marketing communications?",
                        verbose_name="Accepts Marketing",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this client should be treated as active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False,
                        help_text="Is this client banned from booking?",
                        verbose_name="Is Banned",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked user account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["first_name", "last_name"],
                "indexes": [
                    models.Index(
                        fields=["company", "phone"],
                        name="clients_cli_company_1e7334_idx",
                    ),
                    models.Index(
                        fields=["company", "email"],
                        name="clients_cli_company_e994a2_idx",
                    ),
                    models.Index(
                        fields=["company", "is_active"],
                        name="clients_cli_company_fde55f_idx",
                    ),
                ],
            },
        ),
    ]
