# Generated by Django 5.2.5 on 2026-01-29 20:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name or CSS class (e.g., 'salon', 'barbershop')",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Type",
                "verbose_name_plural": "Business Types",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Company Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive companies cannot be accessed",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "business_type",
                    models.ForeignKey(
                        help_text="Business type cannot be deleted if companies are using it",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="tenants.businesstype",
                        verbose_name="Business Type",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns and manages this company",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyRolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Basic User"),
                            (2, "Staff"),
                            (3, "Manager"),
                            (4, "Administrator"),
                        ],
                        verbose_name="Role Level",
                    ),
                ),
                (
                    "can_book_appointments",
                    models.BooleanField(
                        default=False, verbose_name="Can Book Appointments"
                    ),
                ),
                (
                    "can_view_own_calendar",
                    models.BooleanField(
                        default=False, verbose_name="Can View Own Calendar"
                    ),
                ),
                (
                    "can_view_all_calendars",
                    models.BooleanField(
                        default=False, verbose_name="Can View All Calendars"
                    ),
                ),
                (
                    "can_apply_discount",
                    models.BooleanField(
                        default=False, verbose_name="Can Apply Discount"
                    ),
                ),
                (
                    "can_view_client_contact",
                    models.BooleanField(
                        default=False, verbose_name="Can View Client Contact Info"
                    ),
                ),
                (
                    "can_download_clients",
                    models.BooleanField(
                        default=False, verbose_name="Can Download Client List"
                    ),
                ),
                (
                    "can_view_services",
                    models.BooleanField(
                        default=False, verbose_name="Can View Services"
                    ),
                ),
                (
                    "can_create_services",
                    models.BooleanField(
                        default=False, verbose_name="Can Create Services"
                    ),
                ),
                (
                    "can_edit_services",
                    models.BooleanField(
                        default=False, verbose_name="Can Edit Services"
                    ),
                ),
                (
                    "can_delete_services",
                    models.BooleanField(
                        default=False, verbose_name="Can Delete Services"
                    ),
                ),
                (
                    "can_checkout",
                    models.BooleanField(default=False, verbose_name="Can Checkout"),
                ),
                (
                    "can_edit_prices",
                    models.BooleanField(default=False, verbose_name="Can Edit Prices"),
                ),
                (
                    "can_void_invoices",
                    models.BooleanField(
                        default=False, verbose_name="Can Void Invoices"
                    ),
                ),
                (
                    "can_view_all_sales",
                    models.BooleanField(
                        default=False, verbose_name="Can View All Sales"
                    ),
                ),
                (
                    "can_view_schedules",
                    models.BooleanField(
                        default=False, verbose_name="Can View Staff Schedules"
                    ),
                ),
                (
                    "can_manage_staff",
                    models.BooleanField(default=False, verbose_name="Can Manage Staff"),
                ),
                (
                    "can_manage_permissions",
                    models.BooleanField(
                        default=False, verbose_name="Can Manage Permissions"
                    ),
                ),
                (
                    "can_run_payroll",
                    models.BooleanField(default=False, verbose_name="Can Run Payroll"),
                ),
                (
                    "can_view_inventory",
                    models.BooleanField(
                        default=False, verbose_name="Can View Inventory"
                    ),
                ),
                (
                    "can_create_products",
                    models.BooleanField(
                        default=False, verbose_name="Can Create Products"
                    ),
                ),
                (
                    "can_import_bulk",
                    models.BooleanField(default=False, verbose_name="Can Bulk Import"),
                ),
                (
                    "can_bulk_operations",
                    models.BooleanField(
                        default=False, verbose_name="Can Perform Bulk Operations"
                    ),
                ),
                (
                    "can_access_reports",
                    models.BooleanField(
                        default=False, verbose_name="Can Access Reports"
                    ),
                ),
                (
                    "can_access_insights",
                    models.BooleanField(
                        default=False, verbose_name="Can Access Advanced Insights"
                    ),
                ),
                (
                    "can_view_team_data",
                    models.BooleanField(
                        default=False, verbose_name="Can View All Team Data"
                    ),
                ),
                (
                    "can_edit_business_info",
                    models.BooleanField(
                        default=False, verbose_name="Can Edit Business Info"
                    ),
                ),
                (
                    "can_manage_locations",
                    models.BooleanField(
                        default=False, verbose_name="Can Manage Locations"
                    ),
                ),
                (
                    "can_manage_billing",
                    models.BooleanField(
                        default=False, verbose_name="Can Manage Billing"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Role Permission",
                "verbose_name_plural": "Company Role Permissions",
                "ordering": ["company", "level"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "role_level",
                    models.IntegerField(
                        choices=[
                            (1, "Basic User"),
                            (2, "Staff"),
                            (3, "Manager"),
                            (4, "Administrator"),
                        ],
                        default=1,
                        help_text="Employee role level (1-4). Owner is not an employee.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Role Level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Employment Status",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly salary (optional, sensitive data)",
                        max_digits=12,
                        null=True,
                        verbose_name="Salary",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        help_text="Date when employee was hired",
                        verbose_name="Hire Date",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Job title or position",
                        max_length=100,
                        verbose_name="Position/Title",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Department"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this employee works for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="tenants.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user account for this employee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["hire_date"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["owner", "-created_at"], name="tenants_com_owner_i_803a73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["is_active", "is_deleted"],
                name="tenants_com_is_acti_f0af06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companyrolepermission",
            index=models.Index(
                fields=["company", "level"], name="tenants_com_company_fc60f1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="companyrolepermission",
            constraint=models.UniqueConstraint(
                fields=("company", "level"), name="unique_company_level_permission"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["company", "status", "is_deleted"],
                name="tenants_emp_company_028c4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["user", "is_deleted"], name="tenants_emp_user_id_cfc314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["role_level", "status"], name="tenants_emp_role_le_cab274_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user",),
                name="unique_active_employee_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "is_active"], name="tenants_pro_company_552604_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["company", "-created_at"], name="tenants_pro_company_e7f3ef_idx"
            ),
        ),
    ]
