# Generated by Django 5.2.5 on 2026-01-13 04:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Basic User'), (2, 'Staff'), (3, 'Manager'), (4, 'Administrator')], verbose_name='Role Level')),
                ('can_book_appointments', models.BooleanField(default=False, verbose_name='Can Book Appointments')),
                ('can_view_own_calendar', models.BooleanField(default=False, verbose_name='Can View Own Calendar')),
                ('can_view_all_calendars', models.BooleanField(default=False, verbose_name='Can View All Calendars')),
                ('can_apply_discount', models.BooleanField(default=False, verbose_name='Can Apply Discount')),
                ('can_view_client_contact', models.BooleanField(default=False, verbose_name='Can View Client Contact Info')),
                ('can_download_clients', models.BooleanField(default=False, verbose_name='Can Download Client List')),
                ('can_view_services', models.BooleanField(default=False, verbose_name='Can View Services')),
                ('can_create_services', models.BooleanField(default=False, verbose_name='Can Create Services')),
                ('can_edit_services', models.BooleanField(default=False, verbose_name='Can Edit Services')),
                ('can_delete_services', models.BooleanField(default=False, verbose_name='Can Delete Services')),
                ('can_checkout', models.BooleanField(default=False, verbose_name='Can Checkout')),
                ('can_edit_prices', models.BooleanField(default=False, verbose_name='Can Edit Prices')),
                ('can_void_invoices', models.BooleanField(default=False, verbose_name='Can Void Invoices')),
                ('can_view_all_sales', models.BooleanField(default=False, verbose_name='Can View All Sales')),
                ('can_view_schedules', models.BooleanField(default=False, verbose_name='Can View Staff Schedules')),
                ('can_manage_staff', models.BooleanField(default=False, verbose_name='Can Manage Staff')),
                ('can_manage_permissions', models.BooleanField(default=False, verbose_name='Can Manage Permissions')),
                ('can_run_payroll', models.BooleanField(default=False, verbose_name='Can Run Payroll')),
                ('can_view_inventory', models.BooleanField(default=False, verbose_name='Can View Inventory')),
                ('can_create_products', models.BooleanField(default=False, verbose_name='Can Create Products')),
                ('can_import_bulk', models.BooleanField(default=False, verbose_name='Can Bulk Import')),
                ('can_bulk_operations', models.BooleanField(default=False, verbose_name='Can Perform Bulk Operations')),
                ('can_access_reports', models.BooleanField(default=False, verbose_name='Can Access Reports')),
                ('can_access_insights', models.BooleanField(default=False, verbose_name='Can Access Advanced Insights')),
                ('can_view_team_data', models.BooleanField(default=False, verbose_name='Can View All Team Data')),
                ('can_edit_business_info', models.BooleanField(default=False, verbose_name='Can Edit Business Info')),
                ('can_manage_locations', models.BooleanField(default=False, verbose_name='Can Manage Locations')),
                ('can_manage_billing', models.BooleanField(default=False, verbose_name='Can Manage Billing')),
            ],
            options={
                'verbose_name': 'Company Role Permission',
                'verbose_name_plural': 'Company Role Permissions',
                'ordering': ['company', 'level'],
            },
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='tenants_emp_role_f9bb35_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='role_level',
            field=models.IntegerField(choices=[(1, 'Basic User'), (2, 'Staff'), (3, 'Manager'), (4, 'Administrator')], default=1, help_text='Employee role level (1-4). Owner is not an employee.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Role Level'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role_level', 'status'], name='tenants_emp_role_le_cab274_idx'),
        ),
        migrations.AddField(
            model_name='companyrolepermission',
            name='company',
            field=models.ForeignKey(help_text='The company this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.company', verbose_name='Company'),
        ),
        migrations.AddIndex(
            model_name='companyrolepermission',
            index=models.Index(fields=['company', 'level'], name='tenants_com_company_fc60f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyrolepermission',
            constraint=models.UniqueConstraint(fields=('company', 'level'), name='unique_company_level_permission'),
        ),
    ]
