# Generated by Django 5.2.5 on 2026-01-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_businesstype_icon"),
        ("tenants", "0002_companyrolepermission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="business_type",
            field=models.ForeignKey(
                help_text="Business type cannot be deleted if companies are using it",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="system.businesstype",
                verbose_name="Business Type",
            ),
        ),
    ]
