# Generated by Django 5.2.5 on 2026-01-14 05:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("system_billing", "0001_initial"),
        (
            "system_subscriptions",
            "0002_subscriptionplan_system_subs_is_acti_ae4507_idx_and_more",
        ),
        ("tenants", "0002_companyrolepermission_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(
                        default=0,
                        help_text="Current SMS credit balance",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Balance",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_balance",
                        to="tenants.company",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Balance",
                "verbose_name_plural": "SMS Balances",
                "indexes": [
                    models.Index(
                        fields=["tenant"], name="tenant_reso_tenant__d81f22_idx"
                    ),
                    models.Index(
                        fields=["balance"], name="tenant_reso_balance_937337_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SmsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("usage", "Usage"),
                            ("refund", "Refund"),
                            ("admin_adjustment", "Admin Adjustment"),
                            ("bonus", "Bonus"),
                        ],
                        max_length=20,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Positive for additions, negative for deductions",
                        verbose_name="Amount",
                    ),
                ),
                (
                    "balance_after",
                    models.IntegerField(
                        help_text="SMS balance after this transaction",
                        verbose_name="Balance After",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional transaction data",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_transactions",
                        to="system_billing.payment",
                        verbose_name="Payment",
                    ),
                ),
                (
                    "sms_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="system_subscriptions.smspackage",
                        verbose_name="SMS Package",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_transactions",
                        to="tenants.company",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Transaction",
                "verbose_name_plural": "SMS Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="tenant_reso_tenant__88fa6c_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="tenant_reso_transac_e95497_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="tenant_reso_created_f5daeb_idx"
                    ),
                ],
            },
        ),
    ]
