# Generated by Django 5.2.5 on 2026-01-29 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "tax_calculation",
                    models.CharField(
                        choices=[
                            ("exclusive", "Retail prices exclude tax"),
                            ("inclusive", "Retail prices include tax"),
                        ],
                        default="exclusive",
                        max_length=20,
                        verbose_name="Tax Calculation",
                    ),
                ),
                (
                    "team_default_language",
                    models.CharField(
                        default="tr", max_length=5, verbose_name="Team Default Language"
                    ),
                ),
                (
                    "client_default_language",
                    models.CharField(
                        default="tr",
                        max_length=5,
                        verbose_name="Client Default Language",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter URL"),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, verbose_name="Website URL"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Settings",
                "verbose_name_plural": "Business Settings",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company",), name="unique_business_settings"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "other_business_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Other Business Type"
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(max_length=255, verbose_name="Address Line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address Line 2"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="District"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "postcode",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postcode"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="ISO country code",
                        max_length=2,
                        verbose_name="Country",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "working_hours",
                    models.JSONField(
                        default=dict,
                        help_text="Format: {'monday': {'start': '09:00', 'end': '18:00'}, 'sunday': null}",
                        verbose_name="Working Hours",
                    ),
                ),
                (
                    "use_location_for_billing",
                    models.BooleanField(
                        default=True, verbose_name="Use Location for Billing"
                    ),
                ),
                (
                    "billing_company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Billing Company Name"
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, verbose_name="Billing Address"),
                ),
                (
                    "billing_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Billing City"
                    ),
                ),
                (
                    "billing_postcode",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Billing Postcode"
                    ),
                ),
                (
                    "invoice_note",
                    models.TextField(blank=True, verbose_name="Invoice Note"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_business_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="additional_locations",
                        to="tenants.businesstype",
                        verbose_name="Additional Business Types",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "main_business_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="main_locations",
                        to="tenants.businesstype",
                        verbose_name="Main Business Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["company", "is_active"],
                        name="business_lo_company_7ec451_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="System records cannot be edited or deleted by tenant",
                        verbose_name="Is System",
                    ),
                ),
                (
                    "source_code",
                    models.SlugField(
                        blank=True,
                        help_text="Reference to platform default (for system records)",
                        verbose_name="Source Code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icon"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["order", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Rate"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Is Default"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Rate",
                "verbose_name_plural": "Tax Rates",
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
    ]
